# =============================================================================
# RAGEngine Docker Compose Configuration
# Production-ready multi-container setup for Breath Diagnostics
# =============================================================================

services:
  # =============================================================================
  # Qdrant Vector Database
  # =============================================================================
  qdrant:
    image: qdrant/qdrant:latest
    container_name: breath-diagnostics-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
      - ./docker/qdrant/config.yaml:/qdrant/config/production.yaml:ro
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - breath-diagnostics-network

  # =============================================================================
  # RAGEngine Backend with HTMX Frontend (Combined Service)
  # =============================================================================
  web-app:
    build:
      context: .
      dockerfile: docker/web-app/Dockerfile
    container_name: breath-diagnostics-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      # Docker Environment
      - DOCKER_ENV=true
      
      # Database Configuration
      - QDRANT_URL=http://qdrant:6333
      
      # Collection Configuration (NEW)
      - DEFAULT_COLLECTION=current_documents
      - AVAILABLE_COLLECTIONS=current_documents,legacy_documents,sop_policy,research_data,clinical_studies
      
      # Document Processing
      - SOURCE_DOCUMENTS_DIR=/app/documents
      - CHUNKING_STRATEGY=${CHUNKING_STRATEGY:-hybrid_hierarchical_semantic}
      - CHUNK_SIZE_TOKENS=${CHUNK_SIZE_TOKENS:-512}
      - CHUNK_OVERLAP_TOKENS=${CHUNK_OVERLAP_TOKENS:-100}
      - VECTOR_DIMENSIONS=${VECTOR_DIMENSIONS:-1536}
      
      # Search Configuration
      - TOP_K_DENSE=${TOP_K_DENSE:-10}
      - TOP_K_SPARSE=${TOP_K_SPARSE:-10}
      - TOP_K_RERANK=${TOP_K_RERANK:-5}
      
      # Content Classification (NEW)
      - AUTO_COLLECTION_ASSIGNMENT=true
      - ENABLE_DOCUMENT_TYPE_DETECTION=true
      
      # System Configuration
      - TZ=${TZ:-UTC}
      
      # Model Provider Configuration
      - MODEL_PROVIDER=${MODEL_PROVIDER:-gemini}
      - OPENAI_MODEL=${OPENAI_MODEL:-o3-2025-04-16}
      - REASONING_EFFORT=${REASONING_EFFORT:-medium}
    secrets:
      - openai_api_key
      - google_api_key
    volumes:
      - documents_data:/app/documents
      - manifests_data:/app/config
      - logs_data:/app/logs
    entrypoint: ["/docker/web-app/entrypoint.sh"]
    command: ["python", "run_web.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - breath-diagnostics-network

# =============================================================================
# Docker Secrets
# =============================================================================
secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  google_api_key:
    file: ./secrets/google_api_key.txt

# =============================================================================
# Named Volumes
# =============================================================================
volumes:
  qdrant_data:
    driver: local
  documents_data:
    driver: local
  manifests_data:
    driver: local
  logs_data:
    driver: local

# =============================================================================
# Custom Network
# =============================================================================
networks:
  breath-diagnostics-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16