# =============================================================================
# RAGEngine Docker Compose - Development Configuration
# Extends the main docker-compose.yml with development-specific settings
# =============================================================================

services:
  # =============================================================================
  # Backend Development Overrides
  # =============================================================================
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: runtime  # Use runtime stage for faster builds
    volumes:
      # Mount source code for hot reloading
      - ./backend:/app:ro
      - ./run_web.py:/app/run_web.py:ro
      # Keep data volumes
      - documents_data:/app/documents
      - manifests_data:/app/config
      - logs_data:/app/logs
    environment:
      # Override for development
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "uvicorn", "web_app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

  # =============================================================================
  # Frontend Development Overrides
  # =============================================================================
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: builder  # Use builder stage for development
    volumes:
      # Mount source code for hot reloading
      - ./RAGEngine-Frontend:/app:ro
      - /app/node_modules  # Anonymous volume for node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8080  # Use host networking for dev
      - NODE_ENV=development
    ports:
      - "5173:5173"  # Vite dev server port
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]

  # =============================================================================
  # Qdrant Development Overrides
  # =============================================================================
  qdrant:
    # Enable debug logging for development
    environment:
      - QDRANT__LOG_LEVEL=DEBUG
    # Expose additional ports for debugging
    ports:
      - "6333:6333"
      - "6334:6334"

# =============================================================================
# Development Volumes
# =============================================================================
volumes:
  # Use bind mounts for easier development
  documents_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/documents
  manifests_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/config
  logs_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs