# =============================================================================
# RAGEngine Docker Compose - Production Configuration
# Production-optimized settings with enhanced security and performance
# =============================================================================

services:
  # =============================================================================
  # Production Backend Configuration
  # =============================================================================
  backend:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    environment:
      # Production optimizations
      - PYTHONOPTIMIZE=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

  # =============================================================================
  # Production Frontend Configuration
  # =============================================================================
  frontend:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m

  # =============================================================================
  # Production Qdrant Configuration
  # =============================================================================
  qdrant:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    environment:
      # Production optimizations
      - QDRANT__SERVICE__MAX_REQUEST_SIZE_MB=32
      - QDRANT__SERVICE__MAX_WORKERS=4
      - QDRANT__STORAGE__PERFORMANCE__MAX_SEARCH_THREADS=4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true

# =============================================================================
# Production Network Configuration
# =============================================================================
networks:
  ragengine-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ragengine-br
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1